resources:
  containers:
  - container: nv-bionic-wasm
    image: nventive/wasm-build:1.2

jobs:
- job: Linux

  container: nv-bionic-wasm

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - checkout: self
    clean: true

  - task: GitVersion@4
    inputs:
      updateAssemblyInfo: false

  - bash: |
      source $(Agent.WorkFolder)/emsdk/emsdk_env.sh
      npm -g install typescript
      npm install
      make
      mono src/nuget/nuget.exe pack src/nuget/uno.sqlite-wasm.nuspec -Version "1.1.0-dev.$(Build.BuildId)" -OutputDirectory "$(build.artifactstagingdirectory)"
    displayName: 'Run make'

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(build.sourcesdirectory)/dist
      Contents: '*.*'
      TargetFolder: $(build.artifactstagingdirectory)/dist
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    # https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: drop
      ArtifactType: Container